language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failutres:
    php: 7.0
  
before_script: 
  - composer self-update
  - composer install --no-interaction --prefer-source --dev

script:
  - phpunit
